service: madhouse-backend

provider:
  name: aws
  runtime: nodejs18.x
  region: ${env:AWS_REGION}
  environment:
    MONGODB_URI: ${env:MONGODB_URI}
    NODE_OPTIONS: --enable-source-maps
   # CODE_SIGNING_PROFILE_ARN: ${env:CODE_SIGNING_PROFILE_ARN}  # Your Signing Profile ARN stored as secret

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - events:PutRule
            - events:PutTargets
            - events:RemoveTargets
            - events:DeleteRule
            - events:ListTargetsByRule
          Resource: "*"

        - Effect: Allow
          Action:
            - lambda:AddPermission
            - lambda:RemovePermission
          Resource: "*"

        - Effect: Allow
          Action:
            - lambda:InvokeFunction
          Resource: "*"

functions:
  createWallet:
    timeout: 600
    memorySize: 2048
    handler: handler.createWallet
    #environment:
    #  CODE_SIGNING_PROFILE_ARN: ${env:CODE_SIGNING_PROFILE_ARN}  # Pass the ARN to function
    events:
      - httpApi:
          path: /wallets
          method: POST
          cors: true

  getWallets:
    timeout: 600
    memorySize: 2048
    handler: handler.getWallets
    #environment:
     # CODE_SIGNING_PROFILE_ARN: ${env:CODE_SIGNING_PROFILE_ARN}  # Pass the ARN to function
    events:
      - httpApi:
          path: /wallets
          method: GET
          cors: true

  getWalletById:
    timeout: 600
    memorySize: 2048
    handler: handler.getWalletById
    #environment:
     # CODE_SIGNING_PROFILE_ARN: ${env:CODE_SIGNING_PROFILE_ARN}  # Pass the ARN to function
    events:
      - httpApi:
          path: /wallets/{id}
          method: GET
          cors: true

  updateWallet:
    timeout: 600
    memorySize: 2048
    handler: handler.updateWallet
    #environment:
     # CODE_SIGNING_PROFILE_ARN: ${env:CODE_SIGNING_PROFILE_ARN}  # Pass the ARN to function
    events:
      - httpApi:
          path: /wallets/{id}
          method: PUT
          cors: true

  deleteWallet:
    timeout: 600
    memorySize: 2048
    handler: handler.deleteWallet
   # environment:
    #  CODE_SIGNING_PROFILE_ARN: ${env:CODE_SIGNING_PROFILE_ARN}  # Pass the ARN to function
    events:
      - httpApi:
          path: /wallets/{id}
          method: DELETE
          cors: true

plugins:
  - serverless-offline

package:
  patterns:
    - '!node_modules/**'
    - '!*.test.js'
    - '**/*'
