service: madhouse-backend

provider:
  name: aws
  runtime: nodejs18.x
  region: ${env:AWS_REGION}
  environment:
    MONGO_URI: ${env:MONGODB_URI}
    NODE_OPTIONS: --enable-source-maps 

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - events:PutRule
            - events:PutTargets
            - events:RemoveTargets
            - events:DeleteRule
            - events:ListTargetsByRule
          Resource: "*"

        - Effect: Allow
          Action:
            - lambda:AddPermission
            - lambda:RemovePermission
          Resource: "*"

        - Effect: Allow
          Action:
            - lambda:InvokeFunction
          Resource: "*"

functions:
  createWallet:
    timeout: 600
    memorySize: 2048
    handler: handler.createWallet
    events:
      - httpApi:
          path: /wallets
          method: POST

  getWallets:
    timeout: 600
    memorySize: 2048
    handler: handler.getWallets
    events:
      - httpApi:
          path: /wallets
          method: GET

  getWalletById:
    timeout: 600
    memorySize: 2048
    handler: handler.getWalletById
    events:
      - httpApi:
          path: /wallets/{id}
          method: GET

  updateWallet:
    timeout: 600
    memorySize: 2048
    handler: handler.updateWallet
    events:
      - httpApi:
          path: /wallets/{id}
          method: PUT

  deleteWallet:
    timeout: 600
    memorySize: 2048
    handler: handler.deleteWallet
    events:
      - httpApi:
          path: /wallets/{id}
          method: DELETE

resources:
  Resources:
    CodeSigningConfig:
      Type: AWS::Signer::CodeSigningConfig
      Properties:
        CodeSigningConfigName: myCodeSigningConfig
        AllowedPublishers:
          - Arn: ${env:CODE_SIGNING_PROFILE_ARN}


plugins:
  - serverless-offline

package:
  patterns:
    - '!node_modules/**'
    - '!*.test.js'
    - '**/*'



 
